preload = ~/Downloads/wallpapers/flower-gruvbox.jpg
# wallpaper = , ~/Downloads/wallpapers/flower-gruvbox.jpg

wallpaper {
    monitor = DP-1
    file = /home/bsawko/Downloads/wallpapers/flower-gruvbox.jpg
}
