# colors
$fg = ebdbb2
$bg = 282828
$ac = fe8019

$c0  = 282828
$c1  = cc241d
$c2  = 98971a
$c3  = d79921
$c4  = 458588
$c5  = b16286
$c6  = 689d6a
$c7  = d65d0e
$c8  = 928374
$c9  = fb4934
$c10 = b8bb26
$c11 = fabd2f
$c12 = 83a598
$c13 = d3869b
$c14 = 8ec07c
$c15 = ebdbb2

misc {
    font_family = JetBrainsMono Nerd Font
    initial_workspace_tracking = 2
    render_unfocused_fps = 60

    force_default_wallpaper = 0 
    disable_hyprland_logo = true
    vfr = true
}

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    resize_on_border = false
    allow_tearing = false
    layout = hy3

    col.active_border = rgba($c11ff)
    col.inactive_border = rgba($c2ff)
}

group {
    auto_group = true
    groupbar {
        font_size = 12
        height = 16
        indicator_height = 2
        indicator_gap = 2
        keep_upper_gap = false
        gaps_in = 8
        gaps_out = 2

        col.active = rgba($c5ff)
        col.inactive = rgba($c6aa)
    }
}

# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

windowrule {
    name = border-rules
    match:float = 0
    match:workspace = w[tv1]
    # match:workspace = f[1]

    border_size = 0
    rounding = 0
}

windowrule {
    name = topbar-rule
    match:title = quickshell


}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # round corners
    rounding = 0
    rounding_power = 2
    # oppacity
    active_opacity = 1.0
    inactive_opacity = 1.0

    dim_special = 0.3
    dim_around = 1.0

    shadow {
        enabled = true
        range = 32
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 4

        ignore_opacity = false
        new_optimizations = true

        xray = true
        noise = 0
        contrast = 0.8
        brightness = 0.8
        vibrancy = -0.1
        vibrancy_darkness = 1.0

        special = false
        popups = true

        input_methods = false
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = no, fuck off >:(
}

